version: '3.3'

services:
   db:
     image: mongo:3.7
     volumes:
       - dbdata:/mongo-volume
     restart: "no"
     environment:
       MONGO_INITDB_DATABASE: dataex

   dataaex-api:
     depends_on:
       - db
     image: dataex-api:latest
     ports:
       - "3000:3000"
     restart: "always"
     environment:
       MONGO_DB_CONNECTION_STR: mongodb://db:27017/dataex
volumes:
    dbdata:
