version: '3.3'

services:
   db:
     image: mongo:3.7
     container_name: mongodb-container
     ports:
       - "27017:27017"
     volumes:
       - mongo_db_data:/var/lib/mongo_db_volume
       - $PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/
     restart: "no"
     environment:
       MONGO_INITDB_DATABASE: dataex

   dataaex-api:
     depends_on:
       - db
     image: dataex-api:latest
     container_name: dataex-api-container
     ports:
       - "3000:3000"
     restart: "always"
     environment:
       MONGO_DB_CONNECTION_STR: mongodb://db:27017/dataex
volumes:
    mongo_db_data:
